<Project Sdk="Xpf.Sdk/1.6.1">
	<ItemGroup>
		<RuntimeHostConfigurationOption Include="AvaloniaUI.Xpf.LicenseKey" Value="AQAAAHkAAAAfiwgAAAAAAAADY2RgYMhkZAADZsdgzwOFnuIQHgMDCwMDA2tOZl5pBWtuYnJ+MXt5Zl5Kfnkxe1JRfnlxahErSE9FQRpPRUGabmJBpm5xRmYumFOemZeWX5RbzFtanJiealVUmleSmZvKCeEVp2QDAKwQ/m12AAAAAAEAACmZw1cPa5c71tNaasfdOiGHbLtoTRDeOB2aocza4MZZJ7gXgMG1wJBhy11ns7TmUG+HskTrJcdOF2Lsan16jSr9l1JkOjtovdjH7gW/LsAFWchyVcyG9bw1YhA3ZceUIctn6Gj0xn7qrXXns38Xv5/LXPyDvECpVRpVt2wy3v1nICVwO0bCN/VggZg4h7YmOAdyMyztBYwlmpCPWhkRQw+3upkHq+qJpCRbST2ufkOaQ4FSwjUGg7KFERCJX6Fx1+fjJ9bIRaJbz0Cy+UXxHFrcoFIa/0u3GPlC8d/tl2XgG1TBmUi1OnhB69ZPgdv5Pf+eBQ+vSzEWqBLwjhmbr8w=" />
	</ItemGroup>
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DrawingOptions.Shared\DrawingOptions.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="System.IO.Packaging" Version="10.0.4" ExcludeAssets="none" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Avalonia.Desktop" Version="11.3.12" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Repackaged.6.0.System.Drawing.Common" Version="6.0.0" />
	</ItemGroup>

</Project>
